version: "3.9"
services:
  db: 
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
  web:
    build: 
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: docker
      PSQL_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
    command: /bin/sh -c "/usr/src/app/docker-run.sh"
    image: keno/articles-app
    volumes:
      - './:/src'
    ports:
      - "4000:4000"
    links:
      - "db"
    depends_on:
      - "db"
volumes:
  db:
    driver: local